In [1]:
import pandas as pd

# Líneas de transporte de RMBA

## Detalle de empresas de transporte que operan por Jurisdicción Municipal

In [3]:
municipal = pd.read_csv("https://servicios.transporte.gob.ar/gobierno_abierto/descargar.php?t=lineas&d=municipal", sep=";", encoding="UTF-8")
municipal

,anio,jurisdiccion,Empresa,linea
0,09/2019,MUNICIPAL,ALMAFUERTE EMPRESA DE TRANSPORTE S.A.C.I. E I,LINEA 622
1,09/2019,MUNICIPAL,ALMAFUERTE EMPRESA DE TRANSPORTE S.A.C.I. E I,LINEA 628
2,09/2019,MUNICIPAL,AUTOBUSES BS AS SRL- TTE LARRAZABAL SRL- UT,LINEA 514
3,09/2019,MUNICIPAL,AUTOBUSES BUENOS AIRES SRL,LINEA 553 BSAS
4,09/2019,MUNICIPAL,AUTOBUSES BUENOS AIRES SRL,LINEA 540 BSAS
...,...,...,...,...
5584,01/2016,MUNICIPAL,YITOS S.A.,LINEA 543\r
5585,01/2016,MUNICIPAL,YITOS S.A.,LINEA 562\r
5586,01/2016,MUNICIPAL,YITOS S.A.,LINEA 541\r
5587,01/2016,MUNICIPAL,YITOS S.A.,LINEA 561\r
5588,01/2016,MUNICIPAL,YITOS S.A.,LINEA 544\r

## Detalle de empresas de transporte que operan por Jurisdicción Provincial

In [4]:
provincial = pd.read_csv("https://servicios.transporte.gob.ar/gobierno_abierto/descargar.php?t=lineas&d=provincial", sep=";", encoding="UTF-8")
provincial

,anio,jurisdiccion,Empresa,linea
0,09/2019,PROVINCIAL,ALMAFUERTE EMPRESA DE TRANSPORTE S.A.C.I. E I,LINEA 218
1,09/2019,PROVINCIAL,ALMAFUERTE EMPRESA DE TRANSPORTE S.A.C.I. E I,LINEA 284
2,09/2019,PROVINCIAL,ALMAFUERTE EMPRESA DE TRANSPORTE S.A.C.I. E I,LINEA 325
3,09/2019,PROVINCIAL,ALMAFUERTE EMPRESA DE TRANSPORTE S.A.C.I. E I,LINEA 378
4,09/2019,PROVINCIAL,AZUL S.A. DE TRANSPORTE AUTOMOTOR,LINEA 203
...,...,...,...,...
6235,01/2016,PROVINCIAL,VILLA GALICIA SAN JOSE S.A.,LINEA 263A\r
6236,01/2016,PROVINCIAL,VILLA GALICIA SAN JOSE S.A.,LINEA 239B\r
6237,01/2016,PROVINCIAL,VILLA GALICIA SAN JOSE S.A.,LINEA 293A\r
6238,01/2016,PROVINCIAL,VILLA GALICIA SAN JOSE S.A.,LINEA 436\r
6239,01/2016,PROVINCIAL,VILLA NUEVA S.A.,LINEA 257\r

## Detalle de líneas de transporte que operan por Jurisdicción Nacional

In [5]:
nacional = pd.read_csv("https://servicios.transporte.gob.ar/gobierno_abierto/descargar.php?t=lineas&d=nacional", sep=";", encoding="UTF-8")
nacional

         anio jurisdiccion                                Empresa        linea
0     09/2019     NACIONAL                      17 DE AGOSTO S.A.     LINEA 26
1     09/2019     NACIONAL             4 DE SEPTIEMBRE S.A.T.C.P.     LINEA 37
2     09/2019     NACIONAL                ALMAFUERTE S.A.T.A.C.I.     LINEA 55
3     09/2019     NACIONAL      AZUL S.A. DE TRANSPORTE AUTOMOTOR     LINEA 41
4     09/2019     NACIONAL          BERNARDINO RIVADAVIA S.A.T.A.    LINEA 113
...       ...          ...                                    ...          ...
6793  01/2016     NACIONAL      TRANSPORTES QUIRNO COSTA S.A.C.I.  LINEA 103\r
6794  01/2016     NACIONAL       TRANSPORTES SOL DE MAYO C.I.S.A.    LINEA 4\r
6795  01/2016     NACIONAL           TRANSPORTES SUR NOR C.I.S.A.   LINEA 15\r
6796  01/2016     NACIONAL  UNION TRANSPORTISTAS DE EMPRESAS S.A.   LINEA 46\r
6797  01/2016     NACIONAL             VUELTA DE ROCHA S.A.T.C.I.   LINEA 64\r

[6798 rows x 4 columns]